fix #1092 fix manual
latteart-org/latteart pull request #1102
Opened 2023-10-19 08:17 UTC by nemotoaa

2023-10-26 06:47 UTC, fujiwr commented
英語版readmeに記載されている起動方法が古い方式になっています。

2023-10-26 07:34 UTC, fujiwr requested changes

2023-10-26 07:34 UTC, fujiwr commented on docs/startup/pc.md
> +- LatteArt: `latteart.bat`
1つしかないため、「LatteArt: 」は削って、ファイル名だけ記載する形で良いと思います。

2023-10-26 07:34 UTC, fujiwr commented on docs/manual/common/test-result-comparison.md
> +:warning: スクリーンショットの比較は現在 PNG 形式のみ対応しております。 **スクリーンショットの比較を行いたい場合は、テスト記録開始時にメディアタイプを静止画、設定画面の画像圧縮設定を png にしてください。**
静止画＋動画でも比較できたはずなので、「設定画面の画像圧縮設定をpngにしてください」だけで良いと思います。

2023-10-26 07:34 UTC, fujiwr commented on docs/manual/management/manual-management.md
> +また、ストーリーを開いた履歴を過去 5 つ分、左側のメニューバーに「最近読み込んだストーリー」欄に表示されるため、テストマトリクス確認画面からストーリーを開くことなく、ショートカットとしてストーリー編集画面を表示することができます。
誤記: メニューバーに　→　メニューバーの

2023-10-26 07:34 UTC, fujiwr commented on docs/manual/management/manual-management.md
> +  - 記録されたテスト結果を複数読み込むことができます。
```
「実行結果の取り込み」ボタンで記録されたテスト結果を読み込むことができます(複数読み込み可)。
```
のような記述はいかがでしょうか。

2023-10-26 07:34 UTC, fujiwr commented on docs/manual/management/manual-management.md
> +  - セッションに紐づけたテスト結果を新規作成することができます。
```
「新規テストを開始」ボタンでテストを新規で開始することができます。そのテストの結果はセッションに紐づけられます。
```
のような記述はいかがでしょうか。

2023-10-26 07:34 UTC, fujiwr commented on docs/manual/management/manual-management.md
> +また、レビューを行っている間、左側のメニューバーに「現在のレビュー」欄にレビュー画面へのショートカットメニューが表示されるため、ストーリー編集画面など別画面と行き来しながらレビューを行うことができます。
誤記: 左側のメニューバーに → 左側のメニューバーの

2023-10-26 07:34 UTC, fujiwr commented on docs/manual/management/manual-management.md
> +テストマトリクスが 1 つ以上作成されている場合のみボタンが活性化されます。
プレビューで改行されていません。

2023-10-26 07:49 UTC, nemotoaa commented on docs/startup/pc.md
> +- LatteArt: http://127.0.0.1:3000
指摘通り修正致しました。

2023-10-26 07:49 UTC, nemotoaa commented on docs/startup/pc.md
> +- LatteArt: `latteart.bat`
指摘通り修正致しました。

2023-10-26 07:53 UTC, nemotoaa commented on docs/manual/management/manual-management.md
> +また、ストーリーを開いた履歴を過去 5 つ分、左側のメニューバーに「最近読み込んだストーリー」欄に表示されるため、テストマトリクス確認画面からストーリーを開くことなく、ショートカットとしてストーリー編集画面を表示することができます。
指摘通り修正致しました。

2023-10-26 07:53 UTC, nemotoaa commented on docs/manual/management/manual-management.md
> +  - 記録されたテスト結果を複数読み込むことができます。
指摘通り修正致しました。

2023-10-26 07:54 UTC, nemotoaa commented on docs/manual/management/manual-management.md
> +  - セッションに紐づけたテスト結果を新規作成することができます。
指摘通り修正致しました。

2023-10-26 07:54 UTC, nemotoaa commented on docs/manual/management/manual-management.md
> +また、レビューを行っている間、左側のメニューバーに「現在のレビュー」欄にレビュー画面へのショートカットメニューが表示されるため、ストーリー編集画面など別画面と行き来しながらレビューを行うことができます。
指摘通り修正致しました。

2023-10-26 08:41 UTC, nemotoaa commented on docs/manual/management/manual-management.md
> +テストマトリクスが 1 つ以上作成されている場合のみボタンが活性化されます。
指摘通り修正致しました。

2023-10-26 08:45 UTC, nemotoaa commented on docs/manual/common/test-result-comparison.md
> +:warning: スクリーンショットの比較は現在 PNG 形式のみ対応しております。 **スクリーンショットの比較を行いたい場合は、テスト記録開始時にメディアタイプを静止画、設定画面の画像圧縮設定を png にしてください。**
指摘通り修正致しました。

2023-10-26 08:53 UTC, fujiwr approved these changes

2023-10-27 02:36 UTC, masaki-tajima commented
今回、旧記録ツールと旧管理ツールを統合し、「サイドメニュー」からそれぞれの機能を選んで、随時画面を切り替えるようになったため、これに関する記述を丁寧に行いたいです。
サイドメニューそのものの説明が少し欠けていると感じたので、以下を可能な範囲で対応お願いします。

- 画面の説明を最初に行い、「サイドメニュー」（機能を選択するメニュー）と、そこから開かれる「右側の画面」（各機能が表示される画面）があることを（可能であれば画像付きで）紹介
- サイドメニューについて主に以下を説明
  - テスト記録の「テスト記録開始」から、新規にテスト記録が可能
  - テスト記録実施中は、「〇〇」の画面のみ随時切り替えて参照可能
    - 〇〇には、実際に参照可能な機能（例：テストマトリクス確認、設定等）を明示
- 補足情報として以下を紹介
  - テスト記録実施中およびテスト結果の確認中は「テスト結果名」が表示され、記録中には赤丸が表示される
  - 記録中にエラーや何らかの操作が必要なダイアログが表示された場合は、他の画面を表示中の場合でも記録画面に自動で戻る
  - テストマトリクス確認からストーリーを開くと、「最近読み込んだストーリー」に最大5件まで表示される
  - テスト結果をレビューすると、「現在のレビュー」にレビュー中のテスト結果名が表示される
  - サイドメニューは開閉可能

2023-10-27 07:10 UTC, merged