fix #1467 fix manual
latteart-org/latteart pull request #1478
Opened 2024-08-22 02:57 UTC by nemotoaa

2024-08-22 05:10 UTC, mamoru-x-yanagisawa commented on docs/manual/test-design-support/manual-test-design-support.md
> +  :warning: キーワードは編集可能ですが、半角スペース区切りで設定してください。
warningがそのままwarningと表示されてしまっている

2024-08-22 05:15 UTC, mamoru-x-yanagisawa commented on docs/manual/test-design-support/manual-test-design-support.md
> +テスト設計支援では探索的テストを実施する上で有用なテストケース(テストヒント)を登録しておくことで、テスト中に任意のタイミングで表示することができます。
`テストケース(テストヒント)` と記載されていますが、以後テストケースという文言が出てこないのでテストヒントのみの記載で良いのでは。もしくは、`テストヒント(テストケース)` でも。

2024-08-22 05:15 UTC, fujiwr requested changes

2024-08-22 05:15 UTC, fujiwr commented on docs/manual/capture/manual-capture.md
> +#### 検索条件
「マッチング条件について」という見出しの方が良いと思います。

2024-08-22 05:15 UTC, fujiwr commented on docs/manual/capture/manual-capture.md
> +#### 表示順
「現在のテストに関連するヒント」の表示順　という見出しの方が良いと思います。

2024-08-22 05:15 UTC, fujiwr commented on docs/manual/others/manual-config.md
> +  テストヒント検索ダイアログ表示時のマッチング条件の対象範囲のデフォルト値を設定できます。
> テストヒント検索ダイアログ表示時のマッチング条件の対象範囲のデフォルト値を設定できます。

ビュー上では改行されていません。「登録時・検索時のキーワード自動補完対象」と同じようにネストされた箇条書きで表現する形が良いと思います。

2024-08-22 05:15 UTC, fujiwr commented on docs/manual/others/manual-config.md
> +    選択すると、テストヒント登録時は履歴画面で選択した登録対象範囲内に存在するコメントからキーワードを補完します。
ビュー上では改行されていません。ネストされた箇条書きで表現する形が良いと思います。

2024-08-22 05:15 UTC, fujiwr commented on docs/manual/others/manual-config.md
> +    選択すると、テストヒント登録時は履歴画面で選択した登録対象範囲内に存在する画面中のテキストと設定された任意ワードからキーワードを補完します。
ビュー上では改行されていません。ネストされた箇条書きで表現する形が良いと思います。

2024-08-22 05:15 UTC, fujiwr commented on docs/manual/others/manual-config.md
> +    :warning:任意ワードは「コメント内に存在する「画面中のテキスト」及び「任意ワード」からキーワードを補完」が選択時のみ有効となります。
ビュー上では改行されていません。箇条書きで表現する形が良いと思います。

2024-08-22 05:15 UTC, fujiwr commented on docs/manual/others/manual-config.md
> +    キーワード自動補完時に除外したいワードを設定します。
ビュー上では改行されていません。ネストされた箇条書きで表現する形が良いと思います。

2024-08-22 05:15 UTC, fujiwr commented on docs/manual/others/manual-config.md
> +      画面中のテキスト以外の任意のワードをキーワード自動補完対象にしたい場合に設定します。
ビュー上では改行されていません。ネストされた箇条書きで表現する形が良いと思います。

2024-08-22 05:15 UTC, fujiwr commented on docs/manual/others/manual-config.md
> +    :warning: 除外ワードは半角スペース区切りで設定してください。
ビュー上では改行されていません。箇条書きで表現する形が良いと思います。

2024-08-22 05:49 UTC, nemotoaa commented on docs/manual/test-design-support/manual-test-design-support.md
> +  :warning: キーワードは編集可能ですが、半角スペース区切りで設定してください。
修正致しました。

2024-08-22 05:49 UTC, nemotoaa commented on docs/manual/test-design-support/manual-test-design-support.md
> +テスト設計支援では探索的テストを実施する上で有用なテストケース(テストヒント)を登録しておくことで、テスト中に任意のタイミングで表示することができます。
指摘通り修正致しました。

2024-08-22 05:50 UTC, nemotoaa commented on docs/manual/capture/manual-capture.md
> +    - [テストヒントを受けるボタン](#テストヒントを受けるボタン)
全ファイルで「履歴画面」から「テスト結果画面」に変更致しました。

2024-08-22 05:51 UTC, nemotoaa commented on docs/manual/capture/manual-capture.md
> +### テストヒントを受けるボタン
指摘通り修正致しました。

2024-08-22 05:51 UTC, nemotoaa commented on docs/manual/capture/manual-capture.md
> +テスト中に押下するとダイアログが表示され、直近の操作やコメントに近しいテストヒントが一覧で表示されます。
指摘通り修正致しました。

2024-08-22 05:51 UTC, nemotoaa commented on docs/manual/capture/manual-capture.md
> +マッチング結果は（マッチング数/全テストヒント数）で表示されています。
指摘通り修正致しました。

2024-08-22 05:51 UTC, nemotoaa commented on docs/manual/capture/manual-capture.md
> +#### 初期表示時
指摘通り修正致しました。

2024-08-22 05:56 UTC, nemotoaa commented on docs/manual/others/manual-config.md
> +    選択すると、テストヒント登録時は履歴画面で選択した登録対象範囲内に存在する画面中のテキストと設定された任意ワードからキーワードを補完します。
指摘通り修正致しました。

2024-08-22 05:56 UTC, nemotoaa commented on docs/manual/others/manual-config.md
> +    :warning:任意ワードは「コメント内に存在する「画面中のテキスト」及び「任意ワード」からキーワードを補完」が選択時のみ有効となります。
指摘通り修正致しました。

2024-08-22 05:56 UTC, nemotoaa commented on docs/manual/others/manual-config.md
> +    キーワード自動補完時に除外したいワードを設定します。
指摘通り修正致しました。

2024-08-22 05:56 UTC, nemotoaa commented on docs/manual/others/manual-config.md
> +      画面中のテキスト以外の任意のワードをキーワード自動補完対象にしたい場合に設定します。
指摘通り修正致しました。

2024-08-22 05:57 UTC, nemotoaa commented on docs/manual/others/manual-config.md
> +    :warning: 除外ワードは半角スペース区切りで設定してください。
指摘通り修正致しました。

2024-08-22 06:02 UTC, fujiwr commented on docs/manual/capture/manual-capture.md
> +    - [テストヒントを受けるボタン](#テストヒントを受けるボタン)
L128やL549に履歴画面という単語が残っています。

2024-08-22 06:16 UTC, fujiwr requested changes

2024-08-22 06:16 UTC, fujiwr commented on docs/manual/capture/manual-capture.md
> +  :bulb: 初期表示時は「マッチするテストヒントのみ表示」「画面要素」「ヒント本文・キーワード」が有効となっています。
ビュー上で改行されていません。箇条書きで表現する形が良いと思います。

2024-08-22 06:16 UTC, fujiwr commented on docs/manual/capture/manual-capture.md
> -    テストヒント設定を基にコメントを取得し、ヒント本文・キーワード欄に表示します。「自動補完」についての詳細は「[テストヒント設定](../others/manual-config.md/#テストヒント設定)」をご参照ください。
テストヒント設定へのリンクが消えてしまっているため、他の箇所にリンクを載せてください。

2024-08-22 06:40 UTC, nemotoaa commented on docs/manual/capture/manual-capture.md
> +    - [テストヒントを受けるボタン](#テストヒントを受けるボタン)
修正致しました。

2024-08-22 08:46 UTC, fujiwr approved these changes

2024-08-23 04:38 UTC, masaki-tajima commented on docs/manual/capture/manual-capture.md
> +操作一覧のチェックボックスがチェックされた操作をテストヒントの対象範囲としてテストヒントを登録するダイアログを表示します。
チェックされた操作の画面要素とコメントが、テストヒントにおける画面要素とキーワードとして登録ダイアログ内で自動で補完される旨を補足いただけますでしょうか。

2024-08-23 04:46 UTC, masaki-tajima commented on docs/manual/test-design-support/manual-test-design-support.md
> +押下するとカスタムフィールド編集ダイアログが表示され、以下の必須項目以外のカラムを追加・編集・削除することができます。
デフォルトでは「ドメイン特化度」がカスタムフィールドの一つとして用意されており、例えばドメイン特化度:1 では特定のドメインに限定しない汎用的に適用可能なヒントとして、ドメイン特化度:5 では特定のドメインに特化したヒントとしてそれぞれ定義することで、ヒント検索時にドメイン特化度合いの絞込みに活用することができます。
との旨を補足いただけますでしょうか。

2024-08-23 05:25 UTC, fujiwr commented on docs/manual/capture/manual-capture.md
> +操作一覧のチェックボックスがチェックされた操作をテストヒントの対象範囲としてテストヒントを登録するダイアログを表示します。
別ファイルにダイアログの説明を記載してあり、そちらで自動補完については触れているため、ここではその箇所へのリンクを追記いたします。

2024-08-23 08:03 UTC, merged