fix #280 add checkbox filter
latteart-org/latteart pull request #300
Opened 2022-06-02 06:30 UTC by nemotoaa

Signed-off-by: Atsuko Nemoto <98293619+nemotoaa@users.noreply.github.com>

2022-06-02 06:45 UTC, fujiwr requested changes

2022-06-02 06:45 UTC, fujiwr commented on src/gui/locale/message_en.json
> +    "intention": "Purpose",
キー名も`intention`ではなく`purpose`でお願いします。

2022-06-02 06:45 UTC, fujiwr commented on src/gui/vue/pages/operationHistory/organisms/OperationList.vue
> +  private intentionCheckbox = false;
`purposeCheckbox`でお願いします。

2022-06-02 06:45 UTC, fujiwr commented on src/gui/vue/pages/operationHistory/organisms/OperationList.vue
> +.search-checkbox
コンポーネント内に閉じたスタイルは、`scoped`のほうのstyle内に記載してください。

2022-06-02 06:45 UTC, fujiwr commented on src/gui/vue/pages/operationHistory/organisms/OperationList.vue
> +    if (this.intentionCheckbox || this.noticeCheckbox) {
目的と気づきのフィルタについては、`operationIsDisplayed`のように別の関数に分けたほうが良いと思います。

2022-06-02 07:36 UTC, nemotoaa commented on src/gui/locale/message_en.json
> +    "intention": "Purpose",
指摘通り修正致しました。

2022-06-02 07:36 UTC, nemotoaa commented on src/gui/vue/pages/operationHistory/organisms/OperationList.vue
> +  private intentionCheckbox = false;
指摘通り修正致しました。

2022-06-02 07:36 UTC, nemotoaa commented on src/gui/vue/pages/operationHistory/organisms/OperationList.vue
> +    if (this.intentionCheckbox || this.noticeCheckbox) {
指摘通り修正致しました。

2022-06-06 02:47 UTC, fujiwr approved these changes

2022-06-06 02:49 UTC, merged