fix #21 added screenshots dl
latteart-org/latteart pull request #301
Opened 2022-06-07 01:01 UTC by mamoru-x-yanagisawa

Signed-off-by: Mamoru Yanagisawa <72236660+mamoru-x-yanagisawa@users.noreply.github.com>

2022-06-07 07:17 UTC, fujiwr requested changes

2022-06-07 07:17 UTC, fujiwr commented on src/gui/lib/eventDispatcher/repositoryService/ScreenshotsRepository.ts
> +   * @returns URL of the snapshot.
スナップショットになっています。
`URL of the snapshot` -> `URL of the screenshots archive`

2022-06-07 07:17 UTC, fujiwr commented on src/gui/locale/message_ja.json
> +    "generate-screenshots": "スクリーンショットの生成が完了しました。",
スクリーンショットの生成だと、画像を生成しているように思えるため、別のメッセージにしたほうが良いと思います。

2022-06-07 07:17 UTC, fujiwr commented on src/gui/vue/pages/operationHistory/organisms/HistoryDisplay.vue
> +          :testResultId="$store.state.operationHistory.testResultInfo.id"
testResultId属性はコンポーネント内で使われていないようなので消してよいと思います。

2022-06-07 07:17 UTC, fujiwr commented on src/gui/vue/pages/testManagement/ReviewView.vue
> +        :buttonMode="true"
buttonModeというフラグで判断するのではなく、スロットを使う形が良いと思います。

2022-06-07 08:15 UTC, mamoru-x-yanagisawa commented on src/gui/locale/message_ja.json
> +    "generate-screenshots": "スクリーンショットの生成が完了しました。",
スクリーンショットの出力に修正しました。

2022-06-08 01:14 UTC, mamoru-x-yanagisawa commented on src/gui/lib/eventDispatcher/repositoryService/ScreenshotsRepository.ts
> +export class ScreenshotsRepository {
ご指摘の通り修正致しました

2022-06-08 01:14 UTC, mamoru-x-yanagisawa commented on src/gui/lib/eventDispatcher/repositoryService/ScreenshotsRepository.ts
> +   * Create a screenshots of the specified testResult ID.
ご指摘の通り修正しました

2022-06-08 01:15 UTC, mamoru-x-yanagisawa commented on src/gui/lib/eventDispatcher/repositoryService/ScreenshotsRepository.ts
> +   * @returns URL of the snapshot.
ご指摘の通り修正しました

2022-06-08 01:17 UTC, mamoru-x-yanagisawa commented on src/gui/vue/pages/operationHistory/organisms/HistoryDisplay.vue
> +          :testResultId="$store.state.operationHistory.testResultInfo.id"
該当箇所では使用していなかったので削除しました

2022-06-08 01:17 UTC, mamoru-x-yanagisawa commented on src/gui/vue/pages/testManagement/ReviewView.vue
> +        :buttonMode="true"
ご指摘の通り修正致しました

2022-06-08 02:31 UTC, fujiwr approved these changes

2022-06-08 02:49 UTC, merged