add selectall to operationlist
latteart-org/latteart pull request #481
Opened 2022-10-17 02:12 UTC by nemotoaa

Signed-off-by: Atsuko Nemoto <98293619+nemotoaa@users.noreply.github.com>

2022-10-17 03:05 UTC, fujiwr requested changes

2022-10-17 03:05 UTC, fujiwr commented on src/gui/vue/molecules/SelectableDataTable.vue
> +  private get isIndeterminate() {
コンポーネント内のどこがIndeterminate状態なのかがわかりづらいため、`isPartiallyChecked`(部分的にチェックされているか否か)という名称のほうが良いと思いますがいかがでしょうか。

2022-10-17 04:07 UTC, nemotoaa commented on src/gui/vue/molecules/SelectableDataTable.vue
> +  private get isIndeterminate() {
指摘通り修正致しました。

2022-10-17 04:09 UTC, nemotoaa commented on src/gui/vue/molecules/SelectableDataTable.vue
> +  private selected: any[] = [];
指摘通り修正致しました。

2022-10-17 05:16 UTC, nemotoaa commented on src/gui/vue/molecules/SelectableDataTable.vue
> +  private selected: any[] = [];
指摘通り修正致しました。

2022-10-17 05:16 UTC, nemotoaa commented on src/gui/vue/molecules/SelectableDataTable.vue
> +      this.$store.commit("operationHistory/clearCheckedOperations");
指摘通り修正致しました。

2022-10-18 06:41 UTC, fujiwr approved these changes

2022-10-18 06:41 UTC, merged