fix #466 add auto operation manual
latteart-org/latteart pull request #495
Opened 2022-11-02 02:32 UTC by nemotoaa

Signed-off-by: Atsuko Nemoto <98293619+nemotoaa@users.noreply.github.com>

2022-11-02 03:12 UTC, fujiwr requested changes

2022-11-02 03:12 UTC, fujiwr commented on docs/manual/management/manual-management.md
> +- config\_{TimeStamp}.json
他と合わせて`config_YYYYDDMM_HHmmss.json`という記述でお願いします。

2022-11-02 04:37 UTC, fujiwr approved these changes

2022-11-07 03:11 UTC, masaki-tajima commented on docs/manual/capture/manual-capture.md
> +履歴画面-シーケンス図モデルから操作のチェックボックスをチェックし、操作の登録ボタンを押下したときに表示されます。
細かいですが，
- 履歴画面-シーケンス図モデル-操作一覧のチェックボックスをチェックし，・・・
のように，「操作一覧」のチェックボックスを指していることがわかるよう記載お願いします．

2022-11-07 03:11 UTC, masaki-tajima commented on docs/manual/capture/manual-capture.md
> +テスト記録中にフッターから操作の実行ボタンを押下した時に表示されます。
用語の統一化のため，「操作の実行ボタン」==>「自動操作ボタン」でお願いします．

2022-11-07 05:53 UTC, nemotoaa commented on docs/manual/capture/manual-capture.md
指摘通り記載致しました。

2022-11-07 05:53 UTC, nemotoaa commented on docs/manual/capture/manual-capture.md
> +  - 自動操作用の操作セット登録のためのチェックボックスが表示されます。
指摘通り記載致しました。

2022-11-07 05:53 UTC, nemotoaa commented on docs/manual/capture/manual-capture.md
> +履歴画面-シーケンス図モデルから操作のチェックボックスをチェックし、操作の登録ボタンを押下したときに表示されます。
指摘通り記載致しました。

2022-11-07 05:53 UTC, nemotoaa commented on docs/manual/capture/manual-capture.md
> +テスト記録中にフッターから操作の実行ボタンを押下した時に表示されます。
指摘通り記載致しました。

2022-11-07 07:15 UTC, merged