#12 script generate message
latteart-org/latteart pull request #55
Opened 2022-02-04 04:01 UTC by nemotoaa

2022-02-07 07:25 UTC, fujiwr requested changes

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/actions/GenerateTestScriptsAction.ts
> +    const invaridOperationTypeList = params.sources.flatMap((session) => {
booleanの配列を作って後でsomeしていますが、この時点で以下のようにsomeを使ったほうが良いと思います。

```ts
const invalidOperationTypeExists = params.sources.some((session) => {
  return session.history.some((operation) => {
    return invalidOperationTypes.includes(operation.type);
  });
});
```

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/actions/GenerateTestScriptsAction.ts
> +        invaridOperationTypeExists: invaridOperationTypeExists,
keyとvalueの名前が同じ場合はvalueを省略できるため、以下で良いと思います。

```ts
return { outputUrl, invalidOperationTypeExists };
```

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/actions/GenerateTestScriptsAction.ts
> +      return {
keyとvalueの名前が同じ場合はvalueを省略できるため、以下で良いと思います。

```ts
return { outputUrl, invalidOperationTypeExists };
```

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/JSTestScriptCodeGenerator.ts
> +    const untargetedOperations = [
`invalidOperationTypes`が良いと思います、

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/JSTestScriptCodeGenerator.ts
> +    const invaridOperationTypeList = methods.flatMap((method) => {
booleanの配列を作って後でsomeしていますが、この時点で以下のようにsomeを使ったほうが良いと思います。

```ts
const invalidOperationTypeExists = methods.some((method) => {
  return method.operations.some((operation) => {
    return invalidOperationTypes.includes(operation.type);
  });
});
```

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/other/JSDocReadmeGenerator.ts
> +    pageObjectNameToAlias: {
Mapから配列になったので名前を名詞の複数形の形に変更してください。

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/other/JSDocReadmeGenerator.ts
> +    pageObjectNameToAlias: {
Mapから配列になったので名前を名詞の複数形の形に変更してください。

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/other/JSDocReadmeGenerator.ts
> +          return "";
空行が入ってしまいそうな気がしますがよろしいでしょうか。

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/pageObject/JSPageObjectCodeGenerator.ts
> +            return [`// accept_alert`];
`// invalid operation: accept_alert`というように無効な操作であるという旨を記載したほうが良いと思います。
※他の無効なtypeも同様。

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/pageObject/JSPageObjectMethodCommentGenerator.ts
> +          ? `<span style="color:red">Invalid operation type : `
`Invalid operation type: `(コロンの前の空白は無し)の形でお願いします。

2022-02-07 07:25 UTC, fujiwr commented on src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/pageObject/JSPageObjectMethodCommentGenerator.ts
> +  private invalidOperationTypeExists(type: OperationType): boolean {
他の箇所とinvalidOperationTypeの判定基準が違うので、統一する形でお願いします。
※できればロジックを分散させないで１か所にする形を検討してください。

2022-02-07 07:40 UTC, nemotoaa commented on src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/other/JSDocReadmeGenerator.ts
> +          return "";
空の場合はテーブルを表示しないというテストがあり、そういう仕様かと思いましたので、空行を渡す処理を追加致しました。nameとaliasどちらも空の場合は存在しないかと思われるので。

2022-02-08 00:10 UTC, nemotoaa commented on src/gui/lib/operationHistory/actions/GenerateTestScriptsAction.ts
> +    invaridOperationTypeExists: boolean;
指摘通り修正致しました。

2022-02-08 08:21 UTC, fujiwr approved these changes

2022-02-08 08:25 UTC, merged